Attempt at destructuring orb
Broke into multiple files, unfortunately validation fails due to my use of YAML anchors:

> circleci config pack src
Error: Failed trying to marshal the tree to YAML : yaml: unknown anchor 'base-leanpub-params' referenced